### ISSUE TITLE
Don`t work with iOS version 12.1

### ISSUE THREAD

**Issue by ikicodedev** [ysak-y/flutter_audio_capture#8]
The documentation indicates that it is work with iOS 12+, but if you run with iOS 12.1, console show this:

`Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_audio_capture":
      In Podfile:
        flutter_audio_capture (from `.symlinks/plugins/flutter_audio_capture/ios`)

    Specs satisfying the `flutter_audio_capture (from `.symlinks/plugins/flutter_audio_capture/ios`)` dependency were found, but they required a higher minimum deployment target.`

**Comment by ysak-y** [comment]
Could you please share the exact procedure to reproduce it?

If you met this error when trying to run the example app under `example/`, Maybe it's because of following line.

https://github.com/ysak-y/flutter_audio_capture/blob/master/example/ios/Podfile#L2

If so, could you please remove the Podfile and try to run the app by using Xcode?

**Comment by ysak-y** [comment]
I tried and works if set iOS 12.1 when build.
